update

diff --git a/.github/workflows/packages.yml b/.github/workflows/packages.yml
--- a/.github/workflows/packages.yml
+++ b/.github/workflows/packages.yml
@@ -19,30 +19,32 @@ on:
     - 'packages-vh-override/**'
     - 'root-vh-override/**'
     - 'x11-vh-override/**'
-
+  workflow_dispatch:
+    inputs:
+      packages:
+        description: "A space-separated names of packages selected for rebuilding"
+        required: true
+permissions: {} # none
 jobs:
   build:
-    runs-on: ubuntu-latest
-    env:
-      ANDROID_HOME: "/opt/termux/android-sdk"
-      NDK: "/opt/termux/android-ndk"
+    permissions:
+      contents: read # actions/upload-artifact doesn't need contents: write
+    runs-on: ubuntu-22.04
     strategy:
       matrix:
         target_arch: [aarch64, arm, i686, x86_64]
+      fail-fast: false
     steps:
     - name: Setup arm and aarch64 CPU emulators
       uses: dbhi/qus/action@main
       with:
         targets: arm aarch64
     - name: Clone repository
-      uses: actions/checkout@v3
+      uses: actions/checkout@v4
       with:
         fetch-depth: 1000
     - name: Gather build summary
       run: |
-        #################################
-        #### calculate CHANGED_FILES ####
-        #################################
         BASE_COMMIT=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH")
         OLD_COMMIT=$(jq --raw-output .commits[0].id "$GITHUB_EVENT_PATH")
         HEAD_COMMIT=$(jq --raw-output .commits[-1].id "$GITHUB_EVENT_PATH")
@@ -67,133 +69,154 @@ jobs:
           CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r "${BASE_COMMIT}" "HEAD")
         fi
 
-        #################################
-        #### make build dirs         ####
-        #################################
         mkdir -p ./artifacts ./debs
         touch ./debs/.placeholder
 
-        #################################
-        #### edge cases              ####
-        #################################
-        # Process tag '%ci:no-build' that may be added as line to commit message.
-        # Forces CI to cancel current build with status 'passed'.
-        if grep -qiP '^\s*%ci:no-build\s*$' <(git log --format="%B" -n 1 "HEAD"); then
-          tar cf artifacts/debs-${{ matrix.target_arch }}.tar debs
-          echo "[!] Force exiting as tag '%ci:no-build' was applied to HEAD commit message."
-          exit 0
-        fi
-        # Build local Docker image if setup scripts were changed.
-        # Useful for pull requests submitting changes for both build environment and packages.
-        if grep -qP '^scripts/(Dockerfile|setup-ubuntu\.sh)$' <<< "$CHANGED_FILES"; then
-          echo "Detected changes for environment setup scripts. Building custom Docker image now."
-          cd ./scripts
-          docker build -t vanhoavn/vheditor-package-builder:latest . || true
-          cd ..
-        fi
-        #############################################
-        #### create {deleted,built}_packages.txt ####
-        #############################################
-        for repo_path in $(jq --raw-output 'del(.pkg_format) | keys | .[]' repo.json); do
-          repo=$(jq --raw-output '.["'${repo_path}'"].name' repo.json)
-          # Parse changed files and identify new packages and deleted packages.
-          # Create lists of those packages that will be passed to upload job for
-          # further processing.
-          while read -r file; do
-            if ! [[ $file == ${repo_path}/* ]]; then
-              # This file does not belong to a package, so ignore it
-              continue
-            fi
-            if [[ $file =~ ^${repo_path}/([a-z0-9+-]*)/([a-z0-9+-]*).subpackage.sh$ ]]; then
-              # A subpackage was modified, check if it was deleted or just updated
-              pkg=${BASH_REMATCH[1]}
-              subpkg=${BASH_REMATCH[2]}
-              if [ ! -f "${repo_path}/${pkg}/${subpkg}.subpackage.sh" ]; then
-                echo "$subpkg" >> ./deleted_${repo}_packages.txt
+        if [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
+          # Process tag '%ci:no-build' that may be added as line to commit message.
+          # Forces CI to cancel current build with status 'passed'
+          if grep -qiP '^\s*%ci:no-build\s*$' <(git log --format="%B" -n 1 "HEAD"); then
+            tar cf artifacts/debs-${{ matrix.target_arch }}.tar debs
+            echo "[!] Force exiting as tag '%ci:no-build' was applied to HEAD commit message."
+            exit 0
+          fi
+          # Build local Docker image if setup scripts were changed.
+          # Useful for pull requests submitting changes for both build environment and packages.
+          if grep -qP '^scripts/(Dockerfile|properties\.sh|setup-android-sdk\.sh|setup-ubuntu\.sh)$' <<< "$CHANGED_FILES"; then
+            echo "Detected changes for environment setup scripts. Building custom Docker image now."
+            cd ./scripts
+            docker build -t vanhoavn/vheditor-package-builder:latest . || true
+            cd ..
+          fi
+          for repo_path in $(jq --raw-output 'del(.pkg_format) | keys | .[]' repo.json); do
+            repo=$(jq --raw-output '.["'${repo_path}'"].name' repo.json)
+            # Parse changed files and identify new packages and deleted packages.
+            # Create lists of those packages that will be passed to upload job for
+            # further processing.
+            while read -r file; do
+              if ! [[ $file == ${repo_path}/* ]]; then
+                # This file does not belong to a package, so ignore it
+                continue
               fi
-            elif [[ $file =~ ^${repo_path}/([a-z0-9+-]*)/.*$ ]]; then
-              # package, check if it was deleted or updated
-              pkg=${BASH_REMATCH[1]}
-              if [ ! -d "${repo_path}/${pkg}" ]; then
-                echo "$pkg" >> ./deleted_${repo}_packages.txt
-              else
-                echo "$pkg" >> ./built_${repo}_packages.txt
-                # If there are subpackages we want to create a list of those
-                # as well
-                for file in $(find "${repo_path}/${pkg}/" -maxdepth 1 -type f -name \*.subpackage.sh | sort); do
-                  echo "$(basename "${file%%.subpackage.sh}")" >> ./built_${repo}_subpackages.txt
-                done
+              if [[ $file =~ ^${repo_path}/([.a-z0-9+-]*)/([.a-z0-9+-]*).subpackage.sh$ ]]; then
+                # A subpackage was modified, check if it was deleted or just updated
+                pkg=${BASH_REMATCH[1]}
+                subpkg=${BASH_REMATCH[2]}
+                if [ ! -f "${repo_path}/${pkg}/${subpkg}.subpackage.sh" ]; then
+                  echo "$subpkg" >> ./deleted_${repo}_packages.txt
+                fi
+              elif [[ $file =~ ^${repo_path}/([.a-z0-9+-]*)/.*$ ]]; then
+                # package, check if it was deleted or updated
+                pkg=${BASH_REMATCH[1]}
+                if [ -d "${repo_path}/${pkg}" ]; then
+                  echo "$pkg" >> ./built_${repo}_packages.txt
+                  # If there are subpackages we want to create a list of those
+                  # as well
+                  for file in $(find "${repo_path}/${pkg}/" -maxdepth 1 -type f -name \*.subpackage.sh | sort); do
+                    echo "$(basename "${file%%.subpackage.sh}")" >> ./built_${repo}_subpackages.txt
+                  done
+                fi
               fi
-            fi
-          done<<<${CHANGED_FILES}
-          while read -r file; do
-            if ! [[ $file == ${repo_path}-vh-override/* ]]; then
-              continue
-            fi
-            if [[ $file =~ ^${repo_path}-vh-override/([.a-z0-9+-]*)/([.a-z0-9+-]*).subpackage.sh$ ]]; then
-              true
-            elif [[ $file =~ ^${repo_path}-vh-override/([.a-z0-9+-]*)/.*$ ]]; then
-              # package, check if it was deleted or updated
-              pkg=${BASH_REMATCH[1]}
-              if [ ! -d "${repo_path}/${pkg}" ]; then
+            done<<<${CHANGED_FILES}
+            while read -r file; do
+              if ! [[ $file == ${repo_path}-vh-override/* ]]; then
+                # This file does not belong to a package, so ignore it
+                continue
+              fi
+              if [[ $file =~ ^${repo_path}-vh-override/([.a-z0-9+-]*)/([.a-z0-9+-]*).subpackage.sh$ ]]; then
                 true
-              else
+              elif [[ $file =~ ^${repo_path}-vh-override/([.a-z0-9+-]*)/.*$ ]]; then
+                # package, check if it was deleted or updated
+                pkg=${BASH_REMATCH[1]}
+                if [ -d "${repo_path}/${pkg}" ]; then
+                  echo "$pkg" >> ./built_${repo}_packages.txt
+                  for file in $(find "${repo_path}-vh-override/${pkg}/" -maxdepth 1 -type f -name \*.subpackage.sh | sort); do
+                    echo "$(basename "${file%%.subpackage.sh}")" >> ./built_${repo}_subpackages.txt
+                  done
+                  for file in $(find "${repo_path}/${pkg}/" -maxdepth 1 -type f -name \*.subpackage.sh | sort); do
+                    echo "$(basename "${file%%.subpackage.sh}")" >> ./built_${repo}_subpackages.txt
+                  done
+                fi
+              fi
+            done<<<${CHANGED_FILES}
+          done
+        else
+          for pkg in ${{ github.event.inputs.packages }}; do
+            repo_paths=$(jq --raw-output 'del(.pkg_format) | keys | .[]' repo.json)
+            found=false
+            for repo_path in $repo_paths; do
+              repo=$(jq --raw-output '.["'${repo_path}'"].name' repo.json)
+              if [ -d "${repo_path}/${pkg}" ]; then
+                found=true
                 echo "$pkg" >> ./built_${repo}_packages.txt
-                for file in $(find "${repo_path}-vh-override/${pkg}/" -maxdepth 1 -type f -name \*.subpackage.sh | sort); do
-                  echo "$(basename "${file%%.subpackage.sh}")" >> ./built_${repo}_subpackages.txt
-                done
-                for file in $(find "${repo_path}/${pkg}/" -maxdepth 1 -type f -name \*.subpackage.sh | sort); do
-                  echo "$(basename "${file%%.subpackage.sh}")" >> ./built_${repo}_subpackages.txt
+                for subpkg in $(find "${repo_path}/${pkg}/" -maxdepth 1 -type f -name \*.subpackage.sh | sort); do
+                  echo "$(basename "${subpkg%%.subpackage.sh}")" >> ./built_${repo}_subpackages.txt
                 done
               fi
+            done
+            if [ "$found" != true ]; then
+              echo "Package '${pkg}' not found in any of the repo"
+              exit 1
             fi
-          done<<<${CHANGED_FILES}
-        done
+          done
+        fi
 
-        #############################################
-        #### Post processing packages list       ####
-        #############################################
         for repo in $(jq --raw-output 'del(.pkg_format) | .[].name' repo.json); do
           # Fix so that lists do not contain duplicates
           if [ -f ./built_${repo}_packages.txt ]; then
-            uniq ./built_${repo}_packages.txt > ./built_${repo}_packages.txt.tmp
+            sort ./built_${repo}_packages.txt | uniq > ./built_${repo}_packages.txt.tmp
             mv ./built_${repo}_packages.txt.tmp ./built_${repo}_packages.txt
           fi
           if [ -f ./built_${repo}_subpackages.txt ]; then
-            uniq ./built_${repo}_subpackages.txt > ./built_${repo}_subpackages.txt.tmp
+            sort ./built_${repo}_subpackages.txt | uniq > ./built_${repo}_subpackages.txt.tmp
             mv ./built_${repo}_subpackages.txt.tmp ./built_${repo}_subpackages.txt
           fi
           if [ -f ./deleted_${repo}_packages.txt ]; then
-            uniq ./deleted_${repo}_packages.txt > ./deleted_${repo}_packages.txt.tmp
+            sort ./deleted_${repo}_packages.txt | uniq > ./deleted_${repo}_packages.txt.tmp
             mv ./deleted_${repo}_packages.txt.tmp ./deleted_${repo}_packages.txt
           fi
         done
-    - name: Free additional disk space on host
+
+    - name: Lint packages
       run: |
-        if grep -q '^clvk$\|^dart$\|^rust$\|^rustc-nightly$\|^tinygo$\|^zig$' ./built_termux-main_packages.txt || \
-          grep -q '^firefox$' ./built_termux-x11_packages.txt; then
-          echo "Free additional disk space on host"
-          sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|libmono|php|aspnetcore)') \
-            mono-runtime-common monodoc-manual ruby
-          sudo apt autoremove -yq
-          sudo rm -rf /opt/hostedtoolcache /usr/local /usr/share/dotnet /usr/share/swift
-        fi
-    - name: Patch
-      run: ./patch-repo.sh
-    - name: Build
-      run: |
-        declare -a packages
-        echo > ./built_packages.txt
+        declare -a package_recipes
         for repo_path in $(jq --raw-output 'del(.pkg_format) | keys | .[]' repo.json); do
           repo=$(jq --raw-output '.["'${repo_path}'"].name' repo.json)
           if [ -f ./built_${repo}_packages.txt ]; then
-            packages="$packages $(cat ./built_${repo}_packages.txt)"
-            cat ./built_${repo}_packages.txt >> ./built_packages.txt
+            package_recipes="$package_recipes $(cat ./built_${repo}_packages.txt | repo_path=${repo_path} awk '{print ENVIRON["repo_path"]"/"$1"/build.sh"}')"
+          fi
+        done
+
+        if [ ! -z "$package_recipes" ]; then
+          ./scripts/lint-packages.sh $package_recipes
+        fi
+
+    - name: Patch
+      run: ./patch-repo.sh
+
+    - name: Build packages
+      run: |
+        declare -a packages
+        for repo_path in $(jq --raw-output 'del(.pkg_format) | keys | .[]' repo.json); do
+          repo=$(jq --raw-output '.["'${repo_path}'"].name' repo.json)
+
+          if [ -f ./built_${repo}_packages.txt ]; then
+            packages="$packages $(cat ./built_${repo}_packages.txt | tr '\n' ' ')"
           fi
         done
 
         if [ ! -z "$packages" ]; then
-          TERMUX_BUILDER_IMAGE_NAME=vanhoavn/vheditor-package-builder ./scripts/run-docker.sh bash -c "bash ./vh-build-package-wrapper.sh -I -a ${{ matrix.target_arch }}"
+          if grep -qP "(^|\\s)${packages// /($|\\s)|(^|\\s)}($|\\s)" ./scripts/big-pkgs.list; then
+            ./scripts/setup-ubuntu.sh
+            sudo apt install ninja-build
+            sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(aspnetcore|cabal-|dotnet-|ghc-|libmono|php)') \
+              firefox google-chrome-stable microsoft-edge-stable mono-runtime-common monodoc-manual ruby
+            sudo apt autoremove -yq
+            sudo rm -fr /opt/hostedtoolcache /usr/share/dotnet /usr/share/swift
+            TERMUX_BUILDER_IMAGE_NAME=vanhoavn/vheditor-package-builder NDK=$ANDROID_NDK_LATEST_HOME ANDROID_HOME=$ANDROID_SDK_ROOT ./build-package.sh -I -a ${{ matrix.target_arch }} $packages
+          else
+            TERMUX_BUILDER_IMAGE_NAME=vanhoavn/vheditor-package-builder ./scripts/run-docker.sh ./build-package.sh -I -a ${{ matrix.target_arch }} $packages
+          fi
         fi
 
     - name: Generate build artifacts
